# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-22 03:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('character', models.CharField(max_length=100)),
                ('runtime', models.IntegerField()),
                ('watch_date', models.DateTimeField(verbose_name='dated watched')),
                ('directors', models.ManyToManyField(to='blog.Director')),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('netflix', 'Netflix'), ('hulu', 'Hulu'), ('amazon', 'Amazon Prime'), ('tv', 'Television'), ('physical', 'DVD / Blu Ray'), ('other', 'Other')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('supporting', 'Supporting Actor'), ('leading', 'Lead Actor'), ('writing', 'Writer'), ('directing', 'Director')], default='leading', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='platforms',
            field=models.ManyToManyField(to='blog.Platform'),
        ),
        migrations.AddField(
            model_name='movie',
            name='review',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.Review'),
        ),
        migrations.AddField(
            model_name='movie',
            name='role',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.Role'),
        ),
    ]
